import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Bell, Bot, Building2, ChevronDown, CircleUserRound, FileText, Gauge, LayoutDashboard, Menu, MessageSquareText, PlugZap, Search, Settings, ShieldCheck, Sparkles, Users, X } from 'lucide-react'
import Brand from '../components/Brand'
import { incidents } from '../data/mock'

type Page='dashboard'|'incidents'|'analytics'|'communications'|'citizens'|'knowledge'|'integrations'|'settings'
const weekly=[{d:'L',n:21},{d:'M',n:32},{d:'X',n:26},{d:'J',n:41},{d:'V',n:34},{d:'S',n:18},{d:'D',n:15}]
const categories=[{name:'Vía pública',value:34},{name:'Limpieza',value:24},{name:'Alumbrado',value:19},{name:'Parques',value:13},{name:'Otros',value:10}]

export default function AdminPanel(){
 const [page,setPage]=useState<Page>('dashboard'); const [mobile,setMobile]=useState(false)
 return <div className="min-h-screen bg-[#edf2f0] lg:grid lg:grid-cols-[270px_1fr]">
  <Sidebar page={page} setPage={setPage} mobile={false}/>
  <main className="min-w-0">
   <header className="sticky top-0 z-30 flex items-center justify-between border-b border-slate-200 bg-white/90 px-5 py-4 backdrop-blur-xl lg:px-8"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></button><div><div className="text-xs font-bold text-slate-400">Ajuntament de Santa Perpètua</div><h1 className="text-xl font-black text-civic-900">{labels[page]}</h1></div></div><div className="flex items-center gap-2"><button className="hidden rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold md:flex">Últimos 30 días <ChevronDown size={17}/></button><button className="rounded-2xl bg-white p-3 shadow-sm"><Bell size={19}/></button><div className="grid h-11 w-11 place-items-center rounded-2xl bg-civic-900 font-black text-white">AM</div></div></header>
   <div className="p-5 md:p-8">{page==='dashboard'&&<Dashboard/>}{page==='incidents'&&<IncidentManagement/>}{page==='analytics'&&<Analytics/>}{page==='communications'&&<Communications/>}{page==='citizens'&&<Citizens/>}{page==='knowledge'&&<Knowledge/>}{page==='integrations'&&<Integrations/>}{page==='settings'&&<SettingsPage/>}</div>
  </main>
  {mobile&&<div className="fixed inset-0 z-50"><div className="absolute inset-0 bg-black/30" onClick={()=>setMobile(false)}/><div className="relative h-full w-[86%] max-w-xs bg-civic-900 p-5 text-white"><button className="absolute right-4 top-4" onClick={()=>setMobile(false)}><X/></button><Sidebar page={page} setPage={(p)=>{setPage(p);setMobile(false)}} mobile/></div></div>}
 </div>
}
const labels={dashboard:'Resumen ejecutivo',incidents:'Gestión de incidencias',analytics:'Analítica y calidad',communications:'Comunicaciones',citizens:'Ciudadanía',knowledge:'Conocimiento de CivIA',integrations:'Integraciones',settings:'Configuración'}
const menu=[{id:'dashboard',icon:LayoutDashboard,label:'Resumen'},{id:'incidents',icon:FileText,label:'Incidencias'},{id:'analytics',icon:Gauge,label:'Analítica'},{id:'communications',icon:MessageSquareText,label:'Comunicaciones'},{id:'citizens',icon:Users,label:'Ciudadanía'},{id:'knowledge',icon:Bot,label:'CivIA y contenidos'},{id:'integrations',icon:PlugZap,label:'Integraciones'},{id:'settings',icon:Settings,label:'Configuración'}]
function Sidebar({page,setPage,mobile}:{page:Page,setPage:(p:Page)=>void,mobile:boolean}){return <aside className={`${mobile?'':'hidden lg:flex'} bg-civic-900 p-5 text-white lg:min-h-screen lg:flex-col`}><Brand light/><div className="mt-10 text-[10px] font-black uppercase tracking-[.22em] text-white/35">Gestión municipal</div><nav className="mt-4 space-y-1">{menu.map(({id,icon:Icon,label})=><button key={id} onClick={()=>setPage(id as Page)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-bold ${page===id?'bg-white text-civic-900':'text-white/60 hover:bg-white/10'}`}><Icon size={19}/>{label}</button>)}</nav><div className="mt-auto rounded-3xl bg-white/8 p-4"><div className="flex items-center gap-3"><ShieldCheck className="text-amberx"/><div><div className="text-sm font-bold">Entorno de demo</div><div className="text-xs text-white/40">Datos simulados</div></div></div></div><Link to="/" className="mt-4 block rounded-2xl border border-white/10 px-4 py-3 text-center text-sm font-bold text-white/65">Volver a la landing</Link></aside>}

function Dashboard(){return <>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KPI label="Incidencias abiertas" value="38" delta="-12% vs. mes anterior" icon={FileText}/><KPI label="Resueltas en plazo" value="92%" delta="+4,6 puntos" icon={ShieldCheck}/><KPI label="Tiempo medio" value="1 h 42 m" delta="-28 minutos" icon={Gauge}/><KPI label="Usuarios activos" value="8.426" delta="+9,8%" icon={Users}/></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.55fr]"><Card title="Evolución de incidencias" subtitle="Entradas registradas durante la última semana"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={weekly}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#32796c" stopOpacity={.45}/><stop offset="100%" stopColor="#32796c" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="n" stroke="#32796c" strokeWidth={3} fill="url(#g)"/></AreaChart></ResponsiveContainer></div></Card><Card title="Distribución" subtitle="Por categoría"><div className="h-60"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={60} outerRadius={90} paddingAngle={3}>{categories.map((_,i)=><Cell key={i} fill={['#0b2b26','#32796c','#7cb9ac','#f1b74a','#cbd5e1'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2">{categories.map((c,i)=><div key={c.name} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full" style={{background:['#0b2b26','#32796c','#7cb9ac','#f1b74a','#cbd5e1'][i]}}/>{c.name}</div>)}</div></Card></div>
 <div className="mt-6"><IncidentTable compact/></div>
 </>}
function KPI({label,value,delta,icon:Icon}:{label:string,value:string,delta:string,icon:any}){return <div className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-civic-50 text-civic-700"><Icon size={20}/></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">{delta}</span></div><div className="mt-6 text-3xl font-black tracking-tight text-civic-900">{value}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>}
function Card({title,subtitle,children}:{title:string,subtitle:string,children:any}){return <div className="rounded-3xl border border-slate-200 bg-white p-6"><div><h3 className="font-black text-civic-900">{title}</h3><p className="mt-1 text-sm text-slate-400">{subtitle}</p></div><div className="mt-6">{children}</div></div>}
function IncidentManagement(){return <><div className="flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4"><Search size={18} className="text-slate-400"/><input placeholder="Buscar por referencia, ubicación o categoría" className="w-full bg-transparent py-3 outline-none"/></div><button className="rounded-2xl bg-civic-900 px-5 py-3 font-bold text-white">Crear incidencia</button></div><div className="mt-6"><IncidentTable/></div></>}
function IncidentTable({compact=false}:{compact?:boolean}){return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 className="font-black text-civic-900">{compact?'Últimas incidencias':'Todas las incidencias'}</h3><p className="text-sm text-slate-400">Información operativa en tiempo real</p></div><button className="text-sm font-bold text-civic-600">Exportar</button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr>{['Referencia','Incidencia','Zona','Estado','Prioridad','Antigüedad',''].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{incidents.map(i=><tr key={i.id} className="border-t border-slate-100"><td className="px-5 py-4 font-bold text-civic-700">{i.id}</td><td className="px-5 py-4"><b>{i.title}</b><div className="text-xs text-slate-400">{i.category} · {i.citizen}</div></td><td className="px-5 py-4">{i.area}</td><td className="px-5 py-4"><Status text={i.status}/></td><td className="px-5 py-4">{i.priority}</td><td className="px-5 py-4 text-slate-500">{i.age}</td><td className="px-5 py-4"><button className="font-bold text-civic-600">Abrir</button></td></tr>)}</tbody></table></div></div>}
function Status({text}:{text:string}){const cls=text==='Resuelta'?'bg-emerald-100 text-emerald-700':text==='Pendiente'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700';return <span className={`rounded-full px-3 py-1 text-xs font-bold ${cls}`}>{text}</span>}
function Analytics(){return <div className="grid gap-6 xl:grid-cols-2"><Card title="Resolución por área" subtitle="Porcentaje dentro del nivel de servicio"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{a:'Alumbrado',v:96},{a:'Limpieza',v:93},{a:'Parques',v:88},{a:'Movilidad',v:84}]} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" domain={[0,100]}/><YAxis dataKey="a" type="category" width={80}/><Tooltip/><Bar dataKey="v" fill="#32796c" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Calidad del asistente" subtitle="Consultas atendidas por CivIA"><div className="grid grid-cols-2 gap-4"><Mini value="3.842" label="Consultas"/><Mini value="87%" label="Resueltas sin derivación"/><Mini value="4,6/5" label="Valoración"/><Mini value="12 s" label="Tiempo de respuesta"/></div></Card></div>}
function Mini({value,label}:{value:string,label:string}){return <div className="rounded-2xl bg-slate-50 p-5"><div className="text-2xl font-black text-civic-900">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>}
function Communications(){return <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card title="Nueva comunicación" subtitle="Segmenta por barrio, tema y urgencia"><div className="space-y-4"><input className="w-full rounded-2xl bg-slate-50 p-4 outline-none" placeholder="Título"/><textarea className="min-h-36 w-full rounded-2xl bg-slate-50 p-4 outline-none" placeholder="Mensaje"/><select className="w-full rounded-2xl bg-slate-50 p-4"><option>Todo el municipio</option><option>Can Folguera</option><option>La Florida</option></select><button className="w-full rounded-2xl bg-civic-900 p-4 font-bold text-white">Programar envío</button></div></Card><Card title="Comunicaciones recientes" subtitle="Rendimiento y alcance"><div className="space-y-3">{['Corte avenida Barcelona','Cinema a la fresca','Aviso de calor intenso'].map((x,i)=><div key={x} className="flex items-center justify-between rounded-2xl border border-slate-100 p-4"><div><b>{x}</b><div className="text-xs text-slate-400">{[7421,5310,8840][i]} destinatarios</div></div><span className="text-sm font-bold text-civic-600">{[78,65,91][i]}% leído</span></div>)}</div></Card></div>}
function Citizens(){return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KPI label="Usuarios registrados" value="12.480" delta="+6,2%" icon={Users}/><KPI label="Activos mensuales" value="8.426" delta="+9,8%" icon={CircleUserRound}/><KPI label="Avisos consentidos" value="73%" delta="+3,1%" icon={Bell}/><KPI label="Satisfacción" value="4,5/5" delta="+0,2" icon={Sparkles}/></div>}
function Knowledge(){return <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card title="Base de conocimiento" subtitle="Documentos oficiales usados por el asistente"><div className="space-y-3">{['Guía de trámites OAC 2026','Ordenanzas fiscales','Agenda municipal','Recogida de residuos y muebles'].map((x,i)=><div key={x} className="flex items-center justify-between rounded-2xl border border-slate-100 p-4"><div className="flex items-center gap-3"><FileText className="text-civic-600"/><div><b>{x}</b><div className="text-xs text-slate-400">Actualizado hace {i+1} días</div></div></div><Status text="Resuelta"/></div>)}</div></Card><Card title="Control editorial" subtitle="Revisión humana y trazabilidad"><div className="rounded-3xl bg-civic-50 p-6"><Bot className="text-civic-700"/><h3 className="mt-5 font-black">87% de respuestas automáticas</h3><p className="mt-2 text-sm leading-6 text-slate-500">Las consultas sensibles o sin evidencia suficiente se derivan al canal municipal correspondiente.</p></div><button className="mt-4 w-full rounded-2xl bg-civic-900 p-4 font-bold text-white">Añadir documento</button></Card></div>}
function Integrations(){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[{n:'Gestor de incidencias',s:'Conectado'},{n:'Web municipal / RSS',s:'Conectado'},{n:'Sede electrónica',s:'Pendiente'},{n:'Agenda cultural',s:'Conectado'},{n:'Cl@ve',s:'Fase futura'},{n:'Notificaciones push',s:'Conectado'}].map(x=><div key={x.n} className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-civic-50 text-civic-600"><PlugZap/></div><span className="text-xs font-bold text-civic-600">{x.s}</span></div><h3 className="mt-6 font-black text-civic-900">{x.n}</h3><p className="mt-2 text-sm text-slate-500">Conector modular y auditable.</p><button className="mt-5 text-sm font-bold text-civic-600">Configurar</button></div>)}</div>}
function SettingsPage(){return <div className="mx-auto max-w-3xl space-y-5"><Card title="Identidad municipal" subtitle="Personalización visual de la PWA"><div className="grid gap-4 sm:grid-cols-2"><input className="rounded-2xl bg-slate-50 p-4" defaultValue="Santa Perpètua de Mogoda"/><input className="rounded-2xl bg-slate-50 p-4" defaultValue="#0b2b26"/></div></Card><Card title="Seguridad y permisos" subtitle="Roles del personal municipal"><div className="space-y-3">{['Administrador','Responsable de área','Operador','Solo lectura'].map(x=><div key={x} className="flex justify-between rounded-2xl border border-slate-100 p-4"><b>{x}</b><button className="text-sm font-bold text-civic-600">Editar</button></div>)}</div></Card></div>}
