import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Bell, Bot, CalendarDays, Camera, ChevronLeft, ChevronRight, CircleUserRound, FileText, Home, Map, MapPin, Menu, MessageCircle, Navigation, Plus, Search, Send, Settings, ShieldCheck, Sparkles, ThumbsUp, Users, X } from 'lucide-react'
import Brand from '../components/Brand'
import { notices } from '../data/mock'

type Screen = 'home'|'incidents'|'new'|'notices'|'assistant'|'agenda'|'participation'|'services'|'map'|'profile'|'settings'

const incidentList = [
  {id:'CI-2026-1804',title:'Farola apagada',status:'En curso',date:'Hoy, 09:42',color:'bg-amber-100 text-amber-700'},
  {id:'CI-2026-1738',title:'Contenedor desbordado',status:'Resuelta',date:'21 jul., 18:10',color:'bg-emerald-100 text-emerald-700'}
]

export default function CitizenApp(){
  const [screen,setScreen]=useState<Screen>('home')
  const [menu,setMenu]=useState(false)
  const [submitted,setSubmitted]=useState(false)
  const [chat,setChat]=useState<{q:string,a:string}[]>([])
  const [query,setQuery]=useState('')
  const title=useMemo(()=>({home:'Inicio',incidents:'Mis incidencias',new:'Nueva incidencia',notices:'Avisos',assistant:'Asistente CivIA',agenda:'Agenda',participation:'Participación',services:'Servicios',map:'Mapa',profile:'Mi perfil',settings:'Ajustes'}[screen]),[screen])

  const ask=()=>{ if(!query.trim())return; const q=query; setQuery(''); setChat(v=>[...v,{q,a:'Para solicitar la recogida de muebles, elige una franja disponible en Servicios → Recogida de voluminosos. También puedes llamar al 93 000 00 00.'}]) }

  return <div className="min-h-screen bg-[#edf2f0] lg:grid lg:grid-cols-[280px_1fr]">
    <aside className="hidden bg-civic-900 p-6 text-white lg:flex lg:flex-col">
      <Brand light/>
      <div className="mt-10 text-xs font-black uppercase tracking-[.2em] text-white/40">Demo ciudadana</div>
      <nav className="mt-4 space-y-2">{navItems.map(n=><button key={n.id} onClick={()=>setScreen(n.id as Screen)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left font-bold ${screen===n.id?'bg-white text-civic-900':'text-white/65 hover:bg-white/10'}`}><n.icon size={20}/>{n.label}</button>)}</nav>
      <Link to="/" className="mt-auto rounded-2xl border border-white/15 px-4 py-3 text-center text-sm font-bold text-white/80">Volver a la landing</Link>
    </aside>

    <main className="mx-auto min-h-screen w-full max-w-6xl bg-[#f7f9f8] lg:my-5 lg:min-h-[calc(100vh-2.5rem)] lg:rounded-[2.5rem] lg:shadow-soft">
      <header className="sticky top-0 z-20 flex items-center justify-between border-b border-slate-200 bg-white/85 px-5 py-4 backdrop-blur-xl lg:rounded-t-[2.5rem]">
        <div className="flex items-center gap-3"><button className="lg:hidden" onClick={()=>setMenu(true)}><Menu/></button>{screen!=='home'&&<button className="rounded-xl bg-slate-100 p-2" onClick={()=>setScreen('home')}><ChevronLeft size={18}/></button>}<div><div className="text-xs font-bold text-slate-400">Santa Perpètua de Mogoda</div><h1 className="font-black text-civic-900">{title}</h1></div></div>
        <button className="relative rounded-2xl bg-white p-3 shadow-sm"><Bell size={20}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500"/></button>
      </header>

      <div className="p-5 pb-28 md:p-8 lg:pb-8">
        {screen==='home'&&<HomeScreen go={setScreen}/>} 
        {screen==='incidents'&&<Incidents go={setScreen}/>} 
        {screen==='new'&&<NewIncident submitted={submitted} setSubmitted={setSubmitted}/>} 
        {screen==='notices'&&<Notices/>}
        {screen==='assistant'&&<Assistant chat={chat} query={query} setQuery={setQuery} ask={ask}/>} 
        {screen==='agenda'&&<Agenda/>}
        {screen==='participation'&&<Participation/>}
        {screen==='services'&&<Services/>}
        {screen==='map'&&<MapScreen/>}
        {screen==='profile'&&<Profile/>}
        {screen==='settings'&&<SettingsScreen/>}
      </div>

      <nav className="safe-bottom fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-slate-200 bg-white px-2 pt-2 lg:hidden">
        <Bottom icon={Home} label="Inicio" active={screen==='home'} onClick={()=>setScreen('home')}/>
        <Bottom icon={FileText} label="Incidencias" active={screen==='incidents'} onClick={()=>setScreen('incidents')}/>
        <button onClick={()=>setScreen('new')} className="mx-auto -mt-7 grid h-16 w-16 place-items-center rounded-full border-4 border-[#f7f9f8] bg-civic-900 text-white shadow-lg"><Plus/></button>
        <Bottom icon={MessageCircle} label="CivIA" active={screen==='assistant'} onClick={()=>setScreen('assistant')}/>
        <Bottom icon={CircleUserRound} label="Perfil" active={screen==='profile'} onClick={()=>setScreen('profile')}/>
      </nav>
    </main>

    {menu&&<div className="fixed inset-0 z-50 bg-civic-900 p-6 text-white lg:hidden"><div className="flex items-center justify-between"><Brand light compact/><button onClick={()=>setMenu(false)}><X/></button></div><nav className="mt-10 grid gap-2">{navItems.map(n=><button key={n.id} onClick={()=>{setScreen(n.id as Screen);setMenu(false)}} className="flex items-center gap-3 rounded-2xl bg-white/5 px-4 py-4 text-left font-bold"><n.icon/>{n.label}</button>)}</nav></div>}
  </div>
}

const navItems=[
  {id:'home',label:'Inicio',icon:Home},{id:'incidents',label:'Mis incidencias',icon:FileText},{id:'notices',label:'Avisos municipales',icon:Bell},{id:'agenda',label:'Agenda',icon:CalendarDays},{id:'participation',label:'Participación',icon:Users},{id:'services',label:'Servicios',icon:ShieldCheck},{id:'map',label:'Mapa',icon:Map},{id:'assistant',label:'Asistente CivIA',icon:Bot},{id:'profile',label:'Mi perfil',icon:CircleUserRound},{id:'settings',label:'Ajustes',icon:Settings}
]

function HomeScreen({go}:{go:(s:Screen)=>void}){return <>
  <div className="rounded-4xl bg-civic-900 p-7 text-white md:p-9"><div className="text-sm font-bold text-white/55">Bon dia, Marta 👋</div><h2 className="mt-2 text-3xl font-black tracking-tight">¿Qué necesitas hoy?</h2><button onClick={()=>go('new')} className="mt-8 flex w-full items-center justify-between rounded-3xl bg-white p-5 text-left text-civic-900"><span className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-amberx"><Camera/></span><span><b className="block">Comunicar una incidencia</b><small className="text-slate-500">Foto, ubicación y seguimiento</small></span></span><ChevronRight/></button></div>
  <div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4"><Quick icon={Bot} label="Preguntar a CivIA" onClick={()=>go('assistant')}/><Quick icon={Bell} label="Avisos" onClick={()=>go('notices')}/><Quick icon={CalendarDays} label="Agenda" onClick={()=>go('agenda')}/><Quick icon={ShieldCheck} label="Servicios" onClick={()=>go('services')}/></div>
  <div className="mt-8 flex items-end justify-between"><div><div className="text-sm font-bold text-civic-500">Seguimiento</div><h3 className="text-2xl font-black text-civic-900">Tu última incidencia</h3></div><button onClick={()=>go('incidents')} className="text-sm font-bold text-civic-600">Ver todas</button></div>
  <div className="mt-4 rounded-3xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-4"><div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700">En curso</span><h4 className="mt-4 font-black text-civic-900">Farola apagada en paseo de la Florida</h4><p className="mt-1 text-sm text-slate-500">CI-2026-1804 · Hoy, 09:42</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-civic-50"><Navigation className="text-civic-600"/></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-2/3 rounded-full bg-civic-500"/></div><div className="mt-3 flex justify-between text-xs font-bold text-slate-400"><span>Recibida</span><span>Asignada</span><span>Resuelta</span></div></div>
</>}
function Quick({icon:Icon,label,onClick}:{icon:any,label:string,onClick:()=>void}){return <button onClick={onClick} className="rounded-3xl border border-slate-200 bg-white p-5 text-left shadow-sm"><Icon className="text-civic-600"/><div className="mt-6 text-sm font-black text-civic-900">{label}</div></button>}
function Incidents({go}:{go:(s:Screen)=>void}){return <><button onClick={()=>go('new')} className="mb-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-civic-900 px-5 py-4 font-bold text-white"><Plus/>Nueva incidencia</button><div className="space-y-4">{incidentList.map(i=><div key={i.id} className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><span className={`rounded-full px-3 py-1 text-xs font-bold ${i.color}`}>{i.status}</span><h3 className="mt-3 font-black text-civic-900">{i.title}</h3><p className="mt-1 text-sm text-slate-500">{i.id} · {i.date}</p></div><ChevronRight className="text-slate-300"/></div></div>)}</div></>}
function NewIncident({submitted,setSubmitted}:{submitted:boolean,setSubmitted:(v:boolean)=>void}){if(submitted)return <div className="mx-auto max-w-xl rounded-4xl bg-white p-8 text-center shadow-soft"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-emerald-100 text-emerald-600"><ShieldCheck size={38}/></div><h2 className="mt-6 text-2xl font-black text-civic-900">Incidencia enviada</h2><p className="mt-3 text-slate-500">Referencia CI-2026-1843. Te avisaremos cuando cambie de estado.</p><button onClick={()=>setSubmitted(false)} className="mt-7 rounded-2xl bg-civic-900 px-6 py-3 font-bold text-white">Crear otra</button></div>;return <div className="mx-auto max-w-2xl space-y-5"><div className="rounded-4xl border-2 border-dashed border-civic-200 bg-civic-50 p-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-civic-900 text-white"><Camera/></div><h3 className="mt-5 font-black text-civic-900">Añade una fotografía</h3><p className="mt-2 text-sm text-slate-500">En la versión real se abriría la cámara o la galería.</p><button className="mt-5 rounded-2xl bg-white px-5 py-3 font-bold text-civic-900 shadow-sm">Simular fotografía</button></div><div className="rounded-3xl bg-white p-5"><div className="flex items-center gap-3"><Sparkles className="text-amber-500"/><div><div className="text-xs font-bold text-slate-400">Sugerencia de CivIA</div><b>Alumbrado público · 94% de confianza</b></div></div></div><label className="block rounded-3xl bg-white p-5"><span className="text-sm font-bold">Descripción</span><textarea className="mt-3 min-h-28 w-full rounded-2xl bg-slate-50 p-4 outline-none" defaultValue="La farola no se enciende por la noche."/></label><div className="rounded-3xl bg-white p-5"><div className="flex items-center gap-3"><MapPin className="text-civic-600"/><div><b>Ubicación detectada</b><div className="text-sm text-slate-500">Passeig de la Florida, 18</div></div></div></div><button onClick={()=>setSubmitted(true)} className="w-full rounded-2xl bg-civic-900 px-5 py-4 font-bold text-white">Enviar incidencia</button></div>}
function Notices(){return <div className="space-y-4">{notices.map((n,i)=><div key={i} className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><span className="rounded-full bg-civic-100 px-3 py-1 text-xs font-bold text-civic-700">{n.tag}</span><span className="text-xs text-slate-400">{n.time}</span></div><h3 className="mt-4 font-black text-civic-900">{n.title}</h3><p className="mt-2 leading-6 text-slate-500">{n.body}</p></div>)}</div>}
function Assistant({chat,query,setQuery,ask}:{chat:{q:string,a:string}[],query:string,setQuery:(s:string)=>void,ask:()=>void}){return <div className="mx-auto flex min-h-[65vh] max-w-3xl flex-col"><div className="rounded-4xl bg-civic-900 p-6 text-white"><Bot/><h2 className="mt-5 text-2xl font-black">Pregunta en lenguaje natural</h2><p className="mt-2 text-white/60">Información municipal clara, basada en fuentes oficiales.</p></div><div className="flex-1 space-y-4 py-6">{chat.length===0&&<div className="grid gap-3 sm:grid-cols-2">{['¿Cuándo recogen muebles?','¿Cómo me empadrono?','¿Qué actividades hay este fin de semana?','Necesito pedir cita en la OAC'].map(q=><button key={q} onClick={()=>setQuery(q)} className="rounded-2xl border border-slate-200 bg-white p-4 text-left text-sm font-bold">{q}</button>)}</div>}{chat.map((m,i)=><div key={i}><div className="ml-auto max-w-[85%] rounded-3xl rounded-br-md bg-civic-900 p-4 text-white">{m.q}</div><div className="mt-3 max-w-[88%] rounded-3xl rounded-bl-md bg-white p-5 leading-7 shadow-sm">{m.a}</div></div>)}</div><div className="sticky bottom-20 flex gap-2 rounded-3xl border border-slate-200 bg-white p-2 shadow-soft lg:bottom-4"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Escribe tu pregunta…" className="min-w-0 flex-1 bg-transparent px-3 outline-none"/><button onClick={ask} className="grid h-12 w-12 place-items-center rounded-2xl bg-civic-900 text-white"><Send size={19}/></button></div></div>}
function Agenda(){return <div className="grid gap-4 md:grid-cols-2"><Event day="31" month="JUL" title="Cinema a la fresca" place="Parc Central · 22:00"/><Event day="02" month="AGO" title="Mercat de proximitat" place="Plaça de la Vila · 10:00"/><Event day="04" month="AGO" title="Taller familiar de ciència" place="Biblioteca · 17:30"/><Event day="08" month="AGO" title="Ruta patrimonial" place="Museu municipal · 18:00"/></div>}
function Event({day,month,title,place}:{day:string,month:string,title:string,place:string}){return <div className="flex gap-4 rounded-3xl border border-slate-200 bg-white p-5"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-civic-900 text-white"><div className="text-center"><b className="block text-xl">{day}</b><span className="text-[10px]">{month}</span></div></div><div><h3 className="font-black text-civic-900">{title}</h3><p className="mt-2 text-sm text-slate-500">{place}</p><button className="mt-3 text-sm font-bold text-civic-600">Añadir al calendario</button></div></div>}
function Participation(){return <div className="space-y-5"><div className="rounded-4xl bg-amberx p-7"><ThumbsUp/><h2 className="mt-5 text-2xl font-black text-civic-900">Presupuestos participativos 2027</h2><p className="mt-2 text-civic-900/70">Vota los proyectos que consideras prioritarios para el municipio.</p><button className="mt-6 rounded-2xl bg-civic-900 px-5 py-3 font-bold text-white">Participar</button></div><div className="rounded-3xl bg-white p-5"><div className="flex justify-between"><b>Renovación del parque infantil</b><span className="text-sm font-bold text-civic-600">62%</span></div><div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full w-[62%] rounded-full bg-civic-500"/></div></div></div>}
function Services(){return <div className="grid gap-4 sm:grid-cols-2">{['Cita previa OAC','Recogida de muebles','Instalaciones deportivas','Farmacias de guardia','Sede electrónica','Transporte urbano'].map((x,i)=><button key={x} className="flex items-center justify-between rounded-3xl border border-slate-200 bg-white p-5 text-left"><span className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-civic-50 text-civic-600">{i%2?<CalendarDays/>:<ShieldCheck/>}</span><b>{x}</b></span><ChevronRight className="text-slate-300"/></button>)}</div>}
function MapScreen(){return <div className="relative min-h-[65vh] overflow-hidden rounded-4xl bg-[#dfe9e5]"><div className="absolute inset-0 opacity-40 hero-grid"/><div className="absolute left-[22%] top-[28%] grid h-12 w-12 place-items-center rounded-full bg-civic-900 text-white shadow-lg"><MapPin/></div><div className="absolute right-[18%] top-[52%] grid h-12 w-12 place-items-center rounded-full bg-amberx text-civic-900 shadow-lg"><Bell/></div><div className="absolute bottom-5 left-5 right-5 rounded-3xl bg-white p-5 shadow-soft"><b>Mapa municipal</b><p className="mt-1 text-sm text-slate-500">Incidencias, equipamientos y avisos próximos.</p></div></div>}
function Profile(){return <div className="mx-auto max-w-xl"><div className="rounded-4xl bg-white p-7 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-civic-100 text-2xl font-black text-civic-700">MG</div><h2 className="mt-4 text-xl font-black">Marta García</h2><p className="text-sm text-slate-500">marta@example.com</p></div><div className="mt-5 space-y-3">{['Mis datos','Preferencias de avisos','Privacidad','Ayuda y soporte'].map(x=><button key={x} className="flex w-full items-center justify-between rounded-2xl bg-white p-5 font-bold"><span>{x}</span><ChevronRight/></button>)}</div></div>}
function SettingsScreen(){return <div className="mx-auto max-w-xl space-y-4">{['Notificaciones por barrio','Alertas de emergencia','Agenda cultural','Actualizaciones de incidencias'].map((x,i)=><div key={x} className="flex items-center justify-between rounded-2xl bg-white p-5"><div><b>{x}</b><p className="mt-1 text-xs text-slate-500">Configurable por el ciudadano</p></div><div className={`h-7 w-12 rounded-full p-1 ${i<3?'bg-civic-600':'bg-slate-200'}`}><div className={`h-5 w-5 rounded-full bg-white transition ${i<3?'ml-5':''}`}/></div></div>)}</div>}
function Bottom({icon:Icon,label,active,onClick}:{icon:any,label:string,active:boolean,onClick:()=>void}){return <button onClick={onClick} className={`flex flex-col items-center gap-1 py-1 text-[10px] font-bold ${active?'text-civic-700':'text-slate-400'}`}><Icon size={21}/>{label}</button>}
